version: 2.1

orbs:
  hokusai: artsy/hokusai@0.8.0

not_staging_or_release: &not_staging_or_release
  filters:
    branches:
      ignore:
        - staging
        - release

only_master: &only_master
  context: hokusai
  filters:
    branches:
      only: master

workflows:
  build-deploy:
    jobs:
      - hokusai/test:
          <<: *not_staging_or_release

      - hokusai/push:
          name: push-staging-image
          <<: *only_master
          requires:
            - hokusai/test

      - hokusai/deploy-staging:
          <<: *only_master
          project-name: frequency
          requires:
            - push-staging-image
