---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: frequency-release-metrics
spec:
  schedule: 48 * * * *
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          annotations:
            cluster-autoscaler.kubernetes.io/safe-to-evict: 'false'
        spec:
          initContainers:
          - name: setenv
            image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/fortress:production
            imagePullPolicy: Always
            command:
            - python
            - src/load/load.py
            - kubernetes
            - production
            - frequency
            envFrom:
            - configMapRef:
                name: secrets-config
            volumeMounts:
            - name: secrets
              mountPath: /secrets
          containers:
          - name: frequency-release-metrics
            image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/frequency:production
            args:
            - bundle
            - exec
            - rake
            - hourly
            imagePullPolicy: Always
            envFrom:
            - configMapRef:
                name: secrets-config
            - configMapRef:
                name: frequency-environment
            volumeMounts:
            - name: secrets
              mountPath: /secrets
              readOnly: true
            env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          restartPolicy: Never
          serviceAccountName: frequency
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: tier
                    operator: In
                    values:
                    - background
          volumes:
          - name: secrets
            emptyDir: {}

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: frequency-commits-load
spec:
  schedule: 11 3 * * *
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          annotations:
            cluster-autoscaler.kubernetes.io/safe-to-evict: 'false'
        spec:
          initContainers:
          - name: setenv
            image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/fortress:production
            imagePullPolicy: Always
            command:
            - python
            - src/load/load.py
            - kubernetes
            - production
            - frequency
            envFrom:
            - configMapRef:
                name: secrets-config
            volumeMounts:
            - name: secrets
              mountPath: /secrets
          containers:
          - name: frequency-commits-load
            image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/frequency:production
            args:
            - bundle
            - exec
            - rake
            - commits:load
            imagePullPolicy: Always
            envFrom:
            - configMapRef:
                name: secrets-config
            - configMapRef:
                name: frequency-environment
            volumeMounts:
            - name: secrets
              mountPath: /secrets
              readOnly: true
            env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          restartPolicy: Never
          serviceAccountName: frequency
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: tier
                    operator: In
                    values:
                    - background
          volumes:
          - name: secrets
            emptyDir: {}


---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: frequency-vulnerabilities-extract
spec:
  schedule: 01 0 * * *
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          annotations:
            cluster-autoscaler.kubernetes.io/safe-to-evict: 'false'
        spec:
          initContainers:
          - name: setenv
            image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/fortress:production
            imagePullPolicy: Always
            command:
            - python
            - src/load/load.py
            - kubernetes
            - production
            - frequency
            envFrom:
            - configMapRef:
                name: secrets-config
            volumeMounts:
            - name: secrets
              mountPath: /secrets
          containers:
          - name: frequency-vulnerabilities-extract
            image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/frequency:production
            args:
            - bundle
            - exec
            - rake
            - vulnerabilities:extract
            imagePullPolicy: Always
            envFrom:
            - configMapRef:
                name: secrets-config
            - configMapRef:
                name: frequency-environment
            volumeMounts:
            - name: secrets
              mountPath: /secrets
              readOnly: true
            env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          restartPolicy: Never
          serviceAccountName: frequency
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: tier
                    operator: In
                    values:
                    - background
          volumes:
          - name: secrets
            emptyDir: {}
