---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: frequency-release-metrics
spec:
  schedule: "48 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: frequency-release-metrics
              image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/frequency:staging
              command: ["bundle", "exec", "ruby", "script.rb"]
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: frequency-environment
              env:
                - name: DD_AGENT_HOST
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
          restartPolicy: Never
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 1
                  preference:
                    matchExpressions:
                      - key: tier
                        operator: In
                        values:
                          - background
